version: '3.8'
services:
    web:
        build: .
        ports:
            - "80:80"
        depends_on:
            - db
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: exampledatabase
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepassword
        volumes:
            - .:/var/www/html

    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: exampledatabase
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepassword
        ports:
            - "3306:3306"
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data:
