version: '3.8'
services:
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: examplepassword
            MYSQL_DATABASE: exampledatabase
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepassword

    web:
        build: .
        ports:
            - "80:80"
        depends_on:
            - db
        environment:
            MYSQL_HOST: db
            MYSQL_DATABASE: exampledatabase
            MYSQL_USER: exampleuser
            MYSQL_PASSWORD: examplepassword
        volumes:
            - .:/var/www/html
